export const ConfigConsts = {
  ACCESS_TOKEN_EXPIRE: 'ACCESS_TOKEN_EXPIRE',
  JWT_SECRET: 'JWT_SECRET',
  DATABASE_URL: 'DATABASE_URL',
  HOST_NAME: 'HOST_NAME',
  PORT: 'PORT',
  WS_PORT: 'WS_PORT',
  MONGO_URL: 'MONGO_URL',
};
